change from secrets.GITHUB_TOKEN to github.token

diff --git a/.github/workflows/django-migration-test.yml b/.github/workflows/django-migration-test.yml
--- a/.github/workflows/django-migration-test.yml
+++ b/.github/workflows/django-migration-test.yml
@@ -82,6 +82,26 @@ jobs:
           virtualenvs-in-project: true
           installer-parallel: true
 
+      - name: Check Poetry
+        working-directory: ${{ inputs.working_directory }}
+        run: |
+          INSTALL_MSG=$(poetry install --dry-run 2>&1 | tail -1)
+          if [[ "$INSTALL_MSG" != '' ]]; then
+            echo "<h2>:no_entry_sign: Poetry install dry-run failed </h2>" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
+            exit 3
+          fi
+
+      - name: Configure Poetry and install packages
+        working-directory: ${{ inputs.working_directory }}
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          poetry config repositories.repowered ${{ secrets.private_pypi_url}}
+          poetry config http-basic.repowered ${{ secrets.private_pypi_user }} ${{ secrets.private_pypi_password}}
+          poetry install --no-interaction --no-root --no-ansi
+
       - name: Check Django Migrations
         working-directory: ${{ inputs.working_directory }}
         run: |
