do check after install

diff --git a/.github/workflows/django-test-coverage.yml b/.github/workflows/django-test-coverage.yml
--- a/.github/workflows/django-test-coverage.yml
+++ b/.github/workflows/django-test-coverage.yml
@@ -85,17 +85,6 @@ jobs:
         if: steps.cache.outputs.cache-hit == 'true'
         run: echo "/github/home/.local/bin" >> $GITHUB_PATH
 
-      - name: Check Poetry
-        working-directory: ${{ inputs.working_directory }}
-        run: |
-          INSTALL_MSG=$(poetry install --dry-run 2>&1 | tail -1)
-          if [[ "$INSTALL_MSG" != '' ]]; then
-            echo "<h2>:no_entry_sign: Poetry install dry-run failed </h2>" >> $GITHUB_STEP_SUMMARY
-            echo "<h3>You should probably run 'poetry lock' </h3>" >> $GITHUB_STEP_SUMMARY
-            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 3
-          fi
-
       - name: Install Poetry ${{ inputs.poetry_version }}
         if: steps.cache.outputs.cache-hit != 'true'
         uses: snok/install-poetry@v1
@@ -104,6 +93,19 @@ jobs:
           virtualenvs-create: true
           virtualenvs-in-project: true
           installer-parallel: true
+
+      - name: Check Poetry
+        working-directory: ${{ inputs.working_directory }}
+        run: |
+          INSTALL_MSG=$(poetry install --dry-run 2>&1 | tail -1)
+          if [[ "$INSTALL_MSG" != '' ]]; then
+            echo "<summary>:no_entry_sign: Poetry install dry-run failed </summary>" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
+            exit 3
+          fi
+
 
       - name: Configure Poetry and install packages
         working-directory: ${{ inputs.working_directory }}
