zo?

diff --git a/.github/workflows/django-migration-test.yml b/.github/workflows/django-migration-test.yml
--- a/.github/workflows/django-migration-test.yml
+++ b/.github/workflows/django-migration-test.yml
@@ -86,13 +86,13 @@ jobs:
         working-directory: ${{ inputs.working_directory }}
         run: |
           poetry run python manage.py makemigrations --dry-run
-          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-            echo "<h2>:no_entry_sign: Migration check failed </h2>" >> $GITHUB_STEP_SUMMARY
-            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
-            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 3
-          fi
+#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
+#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+#            echo "<h2>:no_entry_sign: Migration check failed </h2>" >> $GITHUB_STEP_SUMMARY
+#            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
+#            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+#            exit 3
+#          fi
         env:
           CI: true
           SQL_DATABASE: ${{ inputs.postgres_db }}
